
###
GET http://localhost:8080/contacts/
###

GET http://localhost:8080/contacts/63c5967ccf966f1306445513

###
GET http://localhost:8080/contacts/63c5967ccf966f1306445514

###
GET http://localhost:8080/contacts/63c5967ccf966f1306445515

###

POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json
Content-Length: <length of the JSON payload>

{
    "firstName": "Future2",
    "lastName": "Janin",
    "email": "future2janinf@gmail.com",
    "favoriteColor": "blue",
    "birthday": "11/25/2023"
}

###

PUT  http://localhost:8080/contacts/63cc6c64a78f9f76b59092ee HTTP/1.1
Content-Type: application/json
Content-Length: <length of the JSON payload>

{
    "firstName": "Future3",
    "lastName": "Janin",
    "email": "future2janinf@gmail.com",
    "favoriteColor": "blue",
    "birthday": "11/25/2023"
}

###
DELETE  http://localhost:8080/contacts/63cc6c64a78f9f76b59092ee HTTP/1.1
Content-Type: application/json
Content-Length: <length of the JSON payload>

{
    "firstName": "Future3",
    "lastName": "Janin",
    "email": "future2janinf@gmail.com",
    "favoriteColor": "blue",
    "birthday": "11/25/2023"
}